### PR TITLE
productionOnly option does the opposite of what is expected

### PR DESCRIPTION
**Pull request by abendigo**
see issue #3

### CODE REVIEW

**Comment by abendigo** [comment]
oh, looks like both changes went into one pull request.. I was trying to do them separately...

**Comment by kenhkan** [comment]
@abendigo I can certainly merge this PR, but just want to make sure why you'd need to use concat-brunch in general. This is written before Brunch had sufficient support of merging files. Is there something that Brunch cannot provide for your use case?

**Comment by abendigo** [comment]
I was writing a service worker, and needed to copy a polyfill from node_modules into public. I couldn't find a straight copy plugin, and concat seemed the closest.

**Comment by kenhkan** [comment]
Merged. Thanks for the PR! :)

**Pull request merged**
